### ISSUE TITLE
Does curated mean regular reviewing correctness of the presented information?

### ISSUE THREAD

**Issue by bigos** [CodyReichert/awesome-cl#107]
IT field changes very quickly. Some package that used to load with (ql:quickload :some-package) may not work any longer. How do you regularly review the correctness of the presented information? Do you rely on new issues? Would it be possible to set up virtual machines with Linux and Windows and run some tests that verify that the packages suggested there at least do install successfully?

**Comment by vindarel** [comment]
Hi, Quicklisp does the checks that the libraries it ships load. Does that answer your main concern ? 

There's also an automatic check for the links on the page on every PR. Not sure if it checks that all links are reachable, I think so.

I've seen once a package being dropped from Quicklisp, but it was added in again the following month.

**Comment by bigos** [comment]
I had a problem with Ceramic. On Windows some of the packages do not work and there is no description anywhere how one could make them work again. In case of Ceramic it was a relatively simple fix. That makes you wonder if Quicklisp checks it only on Linux or MacOSX and what criteria are used to make the packages acceptable.  I guess we have to live with Windows problems, because nothig can be done about it.

**Comment by vindarel** [comment]
For those problematic packages on windows, we could at least add a warning note, and remove them from the list if they have no doc and other contenders.

**Comment by bigos** [comment]
Sometimes there is a relatively easy workaround. In case of ceramic I had to create the Include folder on the C:\ drive and copy the relevant libraries there. So I agree, we need notes.
