### ISSUE TITLE
Awesome lists are curations of the best, not everything.

### ISSUE THREAD

**Issue by azzamsa** [CodyReichert/awesome-cl#114]

**Comment by azzamsa** [comment]
Okay, so I will learn about the packages, before I make any future pull request.

**Comment by vindarel** [comment]
That's the best way, thanks. When unsure just do the PR though, don't worry.

**Comment by vindarel** [comment]
And a reminder that all libraries are on Quickdocs: http://quickdocs.org/ more categories could help, though.
