### ISSUE TITLE
awesome-cl site is not automatically updated

### ISSUE THREAD

**Issue by Hexstream** [CodyReichert/awesome-cl#126]
Based on very limited research, it looks like http://codys.club/awesome-cl/ (redirected from http://codyreichert.github.io/awesome-cl) might be generated from the `gh-pages` branch: https://github.com/CodyReichert/awesome-cl/tree/gh-pages

It seems that that branch was last updated 8 months ago, which might in turn mean that http://codys.club/awesome-cl/ might be pretty stale and might be due to an update?

I wish there was an easy way of ascertaining on what date the site was last updated.

I think someone should look into this. Sorry if I made any incorrect assumptions.

**Comment by vindarel** [comment]
That's right ! It wasn't updated since april (you can see the gh-pages branch). I could update it once I figure how this one works (index.md vs readme.md), but that would be @CodyReichert's to change the way it's built (build it from master ?).

**Comment by Hexstream** [comment]
@CodyReichert At least the [/r/lisp/](https://www.reddit.com/r/lisp/) sidebar (which might be deemed a somewhat prominent location) is linking to the site instead of to the README (as is quite reasonable to do), thus it would be great if the site could be updated at some point...

**Comment by vindarel** [comment]
updated ! It was a manual process though, not optimum.

thanks for the reminder.

**Comment by Hexstream** [comment]
Tremendous! Thank you.

**Comment by vindarel** [comment]
The github page is now automatically updated, isn't it @CodyReichert  ?

**Comment by CodyReichert** [comment]
Yes, now it will update on every commit to master - thanks!

Also, I got a proper domain: https://awesome-cl.com :D
