### ISSUE TITLE
Outdated URL for Ironclad

### ISSUE THREAD

**Issue by glv2** [CodyReichert/awesome-cl#129]
The URL for Ironclad in *awesome-cl* is http://method-combination.net/lisp/ironclad/ (Ironclad v0.32) which is outdated.

Ironclad is currently maintained at https://github.com/sharplispers/ironclad (Ironclad v0.37).

**Comment by vindarel** [comment]
Thanks ! 

(discussion of the move at https://github.com/quicklisp/quicklisp-projects/issues/1303)
