### ISSUE TITLE
Shelly is obsolete

### ISSUE THREAD

**Issue by azzamsa** [CodyReichert/awesome-cl#133]
[OBSOLETE] Make Common Lisp shell-friendly

https://github.com/fukamachi/shelly

**Comment by vindarel** [comment]
Saw that :) https://github.com/CodyReichert/awesome-cl/pull/77

Where we say

> Is there anything Shelly can do that Roswell can't? If not, then I'll merge this, but if there is what do you think about just putting Deprecated on it?

and we didn't move. We surely can mark "deprecated".

**Comment by azzamsa** [comment]
oh Sure thanks. 
Guicho is active somewhere, maybe  he did not notice that mention
