### ISSUE TITLE
Please Replace the Entry for Universal-Config with Ubiquitous

### ISSUE THREAD

**Issue by Shinmera** [CodyReichert/awesome-cl#16]
I failed to mention this on the official project page ([this has since been rectified](https://github.com/Shinmera/Universal-Config/blob/master/README.md)), but Universal-Config has been superseded by [Ubiquitous](https://github.com/Shinmera/ubiquitous). If you could link to that instead, it would be much appreciated.

**Comment by CodyReichert** [comment]
Thanks for the tip, it's changed now.
