### ISSUE TITLE
babel2

### ISSUE THREAD

**Issue by arademaker** [CodyReichert/awesome-cl#19]
add in Natural Language Processing list:

http://emergent-languages.org/Babel2/

**Comment by CodyReichert** [comment]
Done, thanks. The best (shortest) description I could find is "A natural language processing framework". Please let me know if that's incorrect or misleading and I'll update it.

**Comment by arademaker** [comment]
@CodyReichert "An implementation of Fluid Construction Grammar (FCG), a computational framework, and an unification-based grammar formalism that uses feature structures for representing linguistic knowledge."
