### ISSUE TITLE
More suggestions

### ISSUE THREAD

**Issue by kozross** [CodyReichert/awesome-cl#2]
I am not _massively_ knowledgeable about the Common Lisp library and tool-space, and would love suggestions of all sorts.

**Comment by mortality** [comment]
for lisp online tutorials for beginners how about http://www.tutorialspoint.com/lisp/index.htm

**Comment by CodyReichert** [comment]
Hey @mortality, thanks for the suggestion. I think that's a good one to add. Do you want to make a PR?

**Comment by CodyReichert** [comment]
@mortality  - That resource is in the README now, thanks.

**Comment by kozross** [comment]
I just stumbled across [this][1] - is it worth including?

[1]: https://github.com/alvinfrancis/cl-format

**Comment by CodyReichert** [comment]
@kozross It looks like a port of the Common Lisp `format` function for Emacs/Elisp. Definitely a cool ibrary, but it might be better in https://github.com/emacs-tw/awesome-emacs. I don't see it in their list yet, either.

**Comment by vindarel** [comment]
Looks like the suggestions were added :)
