### ISSUE TITLE
Beginner - Practical Common Lisp online

### ISSUE THREAD

**Issue by emaphis** [CodyReichert/awesome-cl#21]
Actually Practical Common Lisp is also online
<http://www.gigamonkeys.com/book/>

**Comment by CodyReichert** [comment]
It is listed in the online _and_ offline sections already: https://github.com/CodyReichert/awesome-cl#beginner

Please re-open if I mis-understand the issue :)

**Comment by emaphis** [comment]
Odd, it does appear in both places in the README.md file and it does appear on the GitHub repository home page, but it doesn't appear on you GitHub.io page:

 <http://codyreichert.github.io/awesome-cl/>

I don't see any thing obviously wrong with the 'md' syntax so I don't know what's up.

**Comment by CodyReichert** [comment]
You're exactly right - I totally forgot to update the site with a few of the newer links. I just pushed an updated version, looks like it's showing correctly in all places now.

Thanks!

**Comment by CodyReichert** [comment]
Makes me think we need a way to update/deploy the GitHub pages site if changes to the README.
