### ISSUE TITLE
Misplaced http-parse package & typo

### ISSUE THREAD

**Issue by mftrhu** [CodyReichert/awesome-cl#220]
The `http-parse` ("An HTTP parser in Common Lisp") package has been put under the "Parsing html" section, but it's a library to parse HTTP requests/responses, and not HTML.

In the same section, there are two typos in the description of Plump - "A lenient HTTP/XML parser, tolerand on malformed markup" should be `s/HTTP/HTML/` and `s/tolerand/tolerant/`.

**Comment by vindarel** [comment]
Thank you !
