### ISSUE TITLE
Is plump in the right category ?

### ISSUE THREAD

**Issue by vindarel** [CodyReichert/awesome-cl#23]
Hi !
Plump is in the XML category, but it's a html/xml parser, tolerant on malformed markup. So it could be in the web category, where is its cousin lquery which plays nice with it (also with [CLSS](https://github.com/Shinmera/CLSS)), so having both or the three side to side could be nice.
Or maybe move XML just below Web. 
Saying that because it would have saved me time.

Cheers !

**Comment by CodyReichert** [comment]
That's a good point -- if it would have saved you some time I can imagine it will save others some time as well.

I'll gladly merge a PR that puts it in the web category.
