### ISSUE TITLE
Suggesting my own project (lisp-machine) update: 404

### ISSUE THREAD

**Issue by cmevident** [CodyReichert/awesome-cl#26]
I saw you listed PORTACLE (which is pretty cool btw) I have a similar project as a docker container

https://github.com/listp/lisp-machine
https://listp.github.io/blog/2016/12/29/a-lisp-machine-in-docker/ (write up)

**Comment by CodyReichert** [comment]
I just installed and ran everything -- this is very cool! We can definitely get this added.

Would you like to send a PR? I think the best spot would be a new section [under Editor Resources](https://github.com/CodyReichert/awesome-cl#text-editor-resources) called IDEs (open to suggestions, though).

**Comment by listp** [comment]
done let me know what you think :D 

https://github.com/CodyReichert/awesome-cl/pull/27

**Comment by listp** [comment]
sorry i just noticed you said under IDE i didn't see a header, feel free to move it if you think it's appropriate

**Comment by vindarel** [comment]
Hi @cmevident 
where has listp/lisp-machine's repo gone ? It gives a 404 now.
I wanted to try it and reference it on Roswell's wiki.
