### ISSUE TITLE
Broken links in readme.md

### ISSUE THREAD

**Issue by CodyReichert** [CodyReichert/awesome-cl#263]
Just wanted to create an issue for some currently broken links (the reason the Assertible badge is red). I should be able to knock these out later today, but wanted to document:

![image](https://user-images.githubusercontent.com/7034627/58193310-5382fa80-7c88-11e9-8cfa-f869c607eaa6.png)

- 404: https://addons.mozilla.org/de/firefox/addon/beautify-practical-common-lisp/?src=search
- 404: http://emergent-languages.org/Babel2/
- server error (50x): http://unlicense.org/

---

@vindarel thanks for keeping on top of everything, I haven't been able to spend much time here as I'd like, but I'm getting caught up. I appreciate the help!

**Comment by vindarel** [comment]
My pleasure !
