### ISSUE TITLE
Add Lisp Koans

### ISSUE THREAD

**Issue by phoe** [CodyReichert/awesome-cl#327]
When https://github.com/google/lisp-koans/pull/111 is merged, I think that the Lisp Koans should be added as a learning resource.

**Comment by phoe** [comment]
The merge was done - I say we're good to go with adding the Koans.

**Comment by Hexstream** [comment]
Thank you for yet another [great contribution](https://github.com/google/lisp-koans/pull/111)! I can't wait for your [GitHub Sponsors](https://github.com/sponsors)!

**Comment by phoe** [comment]
![Zrzut ekranu z 2020-05-09 22-04-49](https://user-images.githubusercontent.com/15045546/81483789-1d47dd80-9241-11ea-932d-24caee808eb0.png)

In meantime, https://www.patreon.com/phoe_krk

**Comment by Hexstream** [comment]
Right, but I'd much rather support people only on GitHub Sponsors to incite everyone to standardize on GitHub to unify the community. ;P

I hope you'll also support bigger tiers on GitHub Sponsors.

**Comment by phoe** [comment]
I care little about standardizing on GitHub to unify the community, especially given GitHub's corporate roots, so sorry, that argument isn't working for me.

Also, it's off-topic; let's just focus on awesome-cl here.

**Comment by vindarel** [comment]
Great addition!

**Comment by phoe** [comment]
Oh. Welp. I was stupid! The Koans were already there!

![Zrzut ekranu z 2020-05-10 13-16-26](https://user-images.githubusercontent.com/15045546/81497715-76a32180-92c0-11ea-88b5-846ffd2a284b.png)

I'm sorry, should have looked at the list - please revert the commit.

**Comment by vindarel** [comment]
and it was already there… twice! (twice before my commit^^)
