### ISSUE TITLE
Link to cl-advice repository is broken

### ISSUE THREAD

**Issue by contrapunctus-1** [CodyReichert/awesome-cl#354]
I looked for repositories of the same name on GitHub, GitLab.com, and common-lisp.net. No luck.

**Comment by vindarel** [comment]
Fortunately I had made a copy: https://github.com/lisp-mirror/budden-tools/search?q=cl-advice&unscoped_q=cl-advice

However, it is not a library, it is not ready for consumption, and it is not maintained… so is it worth keeping?
