### ISSUE TITLE
Mention "Lisp REPL core dumper"?

### ISSUE THREAD

**Issue by Ambrevar** [CodyReichert/awesome-cl#373]
Hi!  A bit of shameless self-promotion here: what about mentioning 
https://gitlab.com/ambrevar/lisp-repl-core-dumper ?

It's convenient to build specialized images and speed up the REPL startup.  Configuring SLIME or SLY to use it is trivial.

I find that it makes for a much smoother REPL experience :)

**Comment by vindarel** [comment]
OK, I think it fills a need. Can you add a Usage section?

**Comment by Ambrevar** [comment]
You mean in the readme upstream?
Well, the usage is printed out when running the program with `-h` or without argument, so I believe that's enough.  Would you suggest something else?

**Comment by vindarel** [comment]
Well yes, because as a user I want to know what the software does and how before I download and run it^^

So, just copy the `-h` output into the README if it's explanatory enough?

**Comment by Ambrevar** [comment]
> Well yes, because as a user I want to know what the software does and how before I download and run it^^

I tried to explain what the software does in the README.  Would you
suggest more clarifications?  Maybe I should add an example?

> So, just copy the `-h` output into the README if it's explanatory enough?

I'd like to avoid that because it means code/text duplication, paving
the way for out-of-sync documentation :p

**Comment by vindarel** [comment]
An example is always welcome :) You don't say: how to get the software, how to run it with our libraries, how to run it again "the quick way". We might see a `lisp-repl-core-dumper` file: do we just have to download it? Is it a CL executable that will work on my machine? (oh, it's a shell script)

> code/text duplication, paving the way for out-of-sync documentation :p

yes, but users first! And I mean: it's not like you will update this tool several times a week. And you can automate this :)

---

Anyways, PR welcome. Under which section? "developer utilities" maybe.

**Comment by Ambrevar** [comment]
Thanks, this was very useful feedback.

I've updated the readme, it should be clearer now!


> (oh, it's a shell script)

More precisely, it's a mix of POSIX sh and Lisp!  One of the things I
love about Common Lisp is the ability to write this kind of "bootstrap"
scripts, with little POSIX sh and a lot of Common Lisp! :)

> Anyways, PR welcome. Under which section? "developer utilities" maybe.

Yes, "developer utilities" would be a good section.

**Comment by vindarel** [comment]
As a user, I am satisfied and willing to try the tool. (Which I did, see the new issue)

**Comment by vindarel** [comment]
It's in.

**Comment by Ambrevar** [comment]
Thanks!

**Comment by vindarel** [comment]
You're welcome but *you* added it :p
