### ISSUE TITLE
Would like to submit my guide for the list

### ISSUE THREAD

**Issue by ashok-khanna** [CodyReichert/awesome-cl#382]
Hello, I would like to kindly submit my Common Lisp beginner guide for this list. It has had some positive feedback. Thanks in advance for your consideration, and no issue if you deem it not official enough for inclusion.

https://github.com/ashok-khanna/common-lisp-by-example

**Comment by vindarel** [comment]
Hello, it's a nice guide. My suggestion is that you would have the most impact by contributing to the CL Cookbook. It seems your guide covers topics that the Cookbook doesn't (and should). In doing so, you could reference your guide in the "Reference" or "See also" section.

**Comment by ashok-khanna** [comment]
Thanks - that makes sense.

Best wishes,
Ashok

________________________________

**Comment by vindarel** [comment]
(hey, send a PR if you wish)

**Comment by ashok-khanna** [comment]
I might do a re-write with some additional sections, but there's so many books that cover Lisp well - this was just another angle (which is focused on quickly getting up to speed with the basics).

What do you think of [https://pdf.math.dev](https://pdf.math.dev)? (Best viewed in Chrome Desktop)

I was thinking we could convert some of the Lisp materials to an alternate form with higher quality typesetting like in the preceding link? If that's something of interest, let me know which materials you would like to convert and I can try and do so when I have some time.
