### ISSUE TITLE
common-lisp-stat isn't "awesome"

### ISSUE THREAD

**Issue by nathanvy** [CodyReichert/awesome-cl#384]
Under "Statistics" the only recommended library is common-lisp-stat which hasn't seen a commit since 2018 and at the top of the README features a giant marquee reading "status: improving".  Elsewhere in the readme text there are several references to the library being in a pre-alpha state at best.  Those things alone were enough to warn me off using that library.

I don't know of a better stats library but common-lisp-stat doesn't seem like it's complete and in fact seems abandoned.

**Comment by vindarel** [comment]
I think we should keep it somehow in the list, but OK, not pushing it like this. What about:

- we remove the "Statistics" subsection
- we keep the library, but add a note that it's pre-alpha.

So we keep a chance for more people to discover it and join the effort.

**Comment by nathanvy** [comment]
Works for me. If it's the only library out there I don't mind keeping it on
the list at all; the reason I raised the issue is because I was hoping
someone could link to a more complete library.

**Comment by vindarel** [comment]
What do you think of https://lisp-stat.dev/ ? It ships [XLisp-Stat](https://homepage.stat.uiowa.edu/~luke/xls/xlsinfo/) and newer libraries (some abandonned, some still in activity): https://github.com/Lisp-Stat

https://news.ycombinator.com/item?id=26632429#26652655

**Comment by Symbolics** [comment]
Just a point of clarification: except for <10 lines of code related to variable definition, Lisp-Stat does not ship any of **X**Lisp-Stat. We do ship a compatibility library,  [XLS-compat](https://github.com/Lisp-Stat/XLS-compat), who's purpose is to ease porting from the [XLisp-Stat code repository](https://lisp-stat.dev/docs/reference/xlisp/). The systems have different origins, and I recently updated the overview with an explanation on the [relationship to XLisp-Stat](https://lisp-stat.dev/docs/overview/#relationship-to-xlisp-stat). All of the libraries shipped in Lisp-Stat are actively maintained and used. They _were_ abandoned, but have now been adopted and given a new home.
