### ISSUE TITLE
Any take on GrammaTech cl-utils?

### ISSUE THREAD

**Issue by Ambrevar** [CodyReichert/awesome-cl#385]
I just had a quick browse at https://github.com/GrammaTech/cl-utils, looks amazing, I wish I had found this gem before!

Any feedback?

**Comment by Hexstream** [comment]
This looks like any of countless "personal utilities libraries", which more experienced Common Lispers generally frown upon.

If the GrammaTech people love it and it improves their productivity, that's great, but I don't see that this should be recommended as "awesome".

**Comment by vindarel** [comment]
Agreed. There are *some* things to pick, but it is a personal utility library I would not *recommend* to other people.

However, I note the demand for a system that ships several utility libraries…

**Comment by Hexstream** [comment]
> However, I note the demand for a system that ships several utility libraries…

I believe that is called "Quicklisp"... ;)

[quickutil](http://quickutil.org/) attempts to solve this problem more specifically.
(I haven't really tried to understand its value, as microlibraries in Quicklisp works great for me.)

**Comment by Ambrevar** [comment]
After briefly browsing the source, it seems that much of the code is already available (in better shape) in other libraries.  String manipulation, file system tools, etc.

`misc.lisp` and `shell.lisp` have some interesting functions however, not sure these are available in any library.
For instance, `xz-pipe` (could be generalized), `aget`, `areplace`, `adrop` (for alist manipulation).

Agreed that this does not register as "awesome" or recommendable.
