### ISSUE TITLE
Link to Consfigurator

### ISSUE THREAD

**Issue by spwhitton** [CodyReichert/awesome-cl#411]
Hello,

Thank you for linking to my project, Consfigurator.  However, would you mind updating to link to the project homepage rather than the mirror on github, please?  Or, at least the upstream git repository, if you prefer that to the homepage.

https://spwhitton.name/tech/code/consfigurator/
https://git.spwhitton.name/consfigurator

Thanks!

**Comment by vindarel** [comment]
sure ! 

Best,
