### ISSUE TITLE
cl-gserver lists incorrect license.

### ISSUE THREAD

**Issue by ecyrb** [CodyReichert/awesome-cl#415]
Listed as MIT, but appears to be GNU Affero General Public License v3.0:

https://github.com/mdbergmann/cl-gserver/blob/master/LICENSE

**Comment by mdbergmann** [comment]
Indeed the license has been changed about half a year ago.
I'll make a PR shortly.

**Comment by mdbergmann** [comment]
I think this can be closed.
The 'Sento' entry seems to be OK.
