### ISSUE TITLE
Consider add clunit2

### ISSUE THREAD

**Issue by cage2** [CodyReichert/awesome-cl#419]
Hi!

I think, after some time spent on improvement and testing, `clunit2` could be considered a valid substitute to `clunit` (that appears -unfortunately- not updated anymore).

Would you consider add `clunit2` suite to the list?

Bye!
C.

**Comment by vindarel** [comment]
Hello, ah, we mention clunit. 

You improved it: https://www.reddit.com/r/Common_Lisp/comments/ohs9vp/new_release_of_clunit2_with_a_performance_boost/? 

It lives here: https://notabug.org/cage/clunit2

So yes we can reference clunit2.

But do you know how it compares to FiveAM, or if it's worth referencing the two?

**Comment by cage2** [comment]
On Mon, Sep 27, 2021 at 06:01:26AM -0700, vindarel wrote:
> Hello, ah, we mention clunit.
Hi!


> You improved it: https://www.reddit.com/r/Common_Lisp/comments/ohs9vp/new_release_of_clunit2_with_a_performance_boost/?
>
> It lives here: https://notabug.org/cage/clunit2

Sorry, i clearly missed to add some context in my previous message! :(

Yes clunit is my  fork of clunit and with help  form another person now
has performance comparable with other unit testing framework.

> So yes we can reference clunit2.
>
> But do you know how it compares to FiveAM, or if it's worth referencing the two?

Honestly  i  never used  FiveAm  so  i  can  not make  any  meaningful
comparison, clunit(2) has  all the feature i need from  a unit testing
library and the code is well organized and quite clean. These are very
subjective opinion of course! :)

I just find that is a pity that this list points people to clunit that
is unmaintained but -as  i wrote above- is a good  and useful piece of
software worth to be resurrected, used and even improved! :)

Bye!
C.

**Comment by vindarel** [comment]
Ok thanks. Let me say something maintainers say: PR accepted :)

**Comment by cage2** [comment]
On Wed, Sep 29, 2021 at 02:19:46AM -0700, vindarel wrote:

Hi!

> Ok thanks. Let me say something maintainers say: PR accepted :)

Fine! Should i swap clunit with clunit2?

Bye!
C.

**Comment by vindarel** [comment]
I'm OK with swapping. Thanks!
