### ISSUE TITLE
List of software ?

### ISSUE THREAD

**Issue by vindarel** [CodyReichert/awesome-cl#42]
This list is about libraries. Would that make sense to add a "Software" or "[Open Source] Projects" section ? I'd like a place to reference example CL software, like does [lisp-lang](http://lisp-lang.org/success/), but a real list, to put projects like [Potato](https://www.reddit.com/r/lisp/comments/65v3zx/potato_a_fullfeatured_slacklike_conversations/), Turtl, pgloader (already in this list), and even example websites if I find some… (apart quickdocs).

**Comment by azzamsa** [comment]
Is this enough https://github.com/azzamsa/awesome-cl-software

**Comment by vindarel** [comment]
It is enough, and way better in another place, thanks for the reminder.
