### ISSUE TITLE
Consider replacing cl-fswatch and cl-inotify with file-notify

### ISSUE THREAD

**Issue by contrapunctus-1** [CodyReichert/awesome-cl#442]
I have not used these a whole lot yet, but cl-fswatch is not in the default Quicklisp distribution, and cl-inotify is Linux-only. [file-notify](https://github.com/shinmera/file-notify) is a cross-platform library and is present on Quicklisp.

**Comment by vindarel** [comment]
Makes sense and file-notify seems a clear winner.

cl-fswatch uses fswatch which is cross-platform, but the lisp library isn't, there's a todo.

It would be nice to try them before addition.

I have used cl-inotify a bit.

```lisp
(ql:quickload :cl-inotify)

(bt:make-thread
 (lambda ()
   (cl-inotify:with-inotify (inotify t ("literal-erudite.lisp" :close-write))
     (cl-inotify:do-events (event inotify :blocking-p t)
       (format t "~a~&" event)
       (erudite:erudite #p"literal.md" "literal-erudite.lisp" :output-type :markdown))))
 :name "inotify-erudite")
```
