### ISSUE TITLE
gtwiwtg link dead

### ISSUE THREAD

**Issue by herbertjones** [CodyReichert/awesome-cl#450]
I haven't found another location for it so far either.

**Comment by vindarel** [comment]
thanks.

Looks like this one: https://github.com/d3v3l0/gtwiwtg

He even shows the old url in the install instruction: `git clone https://github.com/cbeo/gtwiwtg /path/to/quicklisp/local-projects/` but IDK if it's the same developper.

**Comment by vindarel** [comment]
I emailed the original author.

**Comment by vindarel** [comment]
it's on https://cicadas.surf/cgit/colin/gtwiwtg.git README: https://cicadas.surf/cgit/colin/gtwiwtg.git/about/ And that URL will be reflected in quicklisp on the next update.
