### ISSUE TITLE
hunchentoot-auth is insecure, and should be removed

### ISSUE THREAD

**Issue by duncan-bayne** [CodyReichert/awesome-cl#463]
The library [hunchentoot-auth](https://github.com/slyrus/hunchentoot-auth) is insecure.  Per its documentation:

>  Note that the password is not directly stored in the
> persistent storage, but rather the password is appended to a random
> (per-user) salt (which is stored in the persistent database) and this
> salted uesr name is then hashed using the MD5 hashing algorithm.

I've [raised an issue](https://github.com/slyrus/hunchentoot-auth/issues/2) on hunchentoot-auth, but in the meantime it should be removed from this collection.

**Comment by vindarel** [comment]
from the twit linked on the issue:

> This is what MD5 hashes look like in hashcat calculating billions of possibilities per second: […]

and confirmation on "billions per second".
