### ISSUE TITLE
Why was unix-opts removed?

### ISSUE THREAD

**Issue by tsilvap** [CodyReichert/awesome-cl#472]
I found out about the [unix-opts](https://github.com/libre-man/unix-opts) library through this page: [Parsing command line arguments | The Common Lisp Cookbook](https://lispcookbook.github.io/cl-cookbook/os.html#parsing-command-line-arguments).

But when I looked for it here, I couldn't find it. Seems like it was listed before, but was removed in this commit: https://github.com/CodyReichert/awesome-cl/commit/d4a2a9c4df1e1a6f1be3de1616bcb5fdfb56adec

Is there any reason for its removal? Just wondering if there's any issues that make it not suitable anymore.

**Comment by vindarel** [comment]
oh-my-god, because this section should be replaced by Clingon! https://vindarel.github.io/cl-cookbook/scripting.html#parsing-command-line-arguments What happened?

unix-opts did the job, but now clingon or again adopt are more feature complete and simpler to use.

**Comment by vindarel** [comment]
super difficult bug, one page was os.html and the other scripting.html :p 

thanks.

So, unix-opts has no issues I am aware of, it's just less "awesome" now compared to the newer libs (and we do some curation on this list).
