### ISSUE TITLE
Actors

### ISSUE THREAD

**Issue by guitarvydas** [CodyReichert/awesome-cl#501]
Actors in Common Lisp: see David Mcclain's implementation, referenced in https://guitarvydas.github.io/2023/10/06/David-McClain-on-FORTH.html. And, my many musings about true message-passing, which I call 0D ("zero dependency").

**Comment by vindarel** [comment]
His actors repo is referenced:

See also:

* [lisp-actors](https://github.com/dbmcclain/Lisp-Actors), an "ongoing investigation into the use of the Actor model in Common Lisp, which has had the benefit of real-world application".
  * it was part of the [Emotiq blockchain](https://github.com/emotiq/emotiq/blob/dev/src/test/blockchain-test.lisp) (a discontinued project)
  * does remoting, includes a threading abstraction layer library similar to Bordeaux-Threads.
  * ! it lacks unit tests.

---

I don't know what project you mean with 0D, feel free to reopen.
