### ISSUE TITLE
What do ⭐ and 👍 mean?

### ISSUE THREAD

**Issue by fehmud** [CodyReichert/awesome-cl#508]
Maybe I'm not smart enough, but I can't understand what  ⭐ and 👍 mean in this list.  For example, the MITO package has a 👍, yet its homepage states that it's at the alpha stage.  Thank you.

**Comment by Hexstream** [comment]
From the README:

> The ones marked with a ⭐ are so widespread and solid that they became community standards. You can't be wrong with them. This is the case for Quicklisp, BordeauxThreads and such. Libraries denoted with a 👍 are the ones we like and want to promote here at the Awesome-cl list. They proved solid, they may solve a problem better than a community standard but they aren't as widespread, or not considered as stable. For example, we prefer Spinneret over Cl-Who.

**Comment by fehmud** [comment]
Darn! I jumped to the list, skipping the introduction. Sorry and thanks (-.-)
