### ISSUE TITLE
Is Elephant Awesome?

### ISSUE THREAD

**Issue by listp** [CodyReichert/awesome-cl#53]
Today I am reminded of the existence of https://common-lisp.net/project/elephant/
Is it awesome?  I wasn't sure if it is i'll add it and make a pull request.

**Comment by CodyReichert** [comment]
Oh cool, that definitely looks awesome and I'll gladly take a PR for it! Have you used it? I didn't try it out, but it seems pretty thorough.

**Comment by listp** [comment]
i've added it in pull/54.  i'ts been around for a very long time.

**Comment by CodyReichert** [comment]
Closed in #54
