### ISSUE TITLE
Missing book and online tutorial

### ISSUE THREAD

**Issue by ryn1x** [CodyReichert/awesome-cl#60]
Casting SPELs in LISP - http://www.lisperati.com/casting.html

The Land of LISP - http://landoflisp.com

An awesome online tutorial and book that are not listed yet.

**Comment by rudolfochrist** [comment]
Land of Lisp is already listed (Learning and Tutorials > Offline > Beginner). Would you mind opening a PR for the castings spells references. I sure this will be merged. :)

**Comment by azzamsa** [comment]
@ryn1x ping :)

**Comment by ryn1x** [comment]
Sorry about that. Pull request sent.
